entrada = input('digite algo :')
print('Só tem espaços ? ', entrada.isspace())
print('Só tem letras maiusculas ? ', entrada.isupper())
print('Só tem letras minusculas ? ', entrada.islower())
print('Só tem numeros ? ', entrada.isnumeric())
print('Só tem letras ? ', entrada.isalpha())
print('Está capitalizada ? ', entrada.istitle())
